In [5]:
import sys
!{sys.executable} -m pip uninstall -y ShAReD_Net

Found existing installation: ShAReD-Net 1.0
Uninstalling ShAReD-Net-1.0:
  Successfully uninstalled ShAReD-Net-1.0


In [2]:
import sys
!{sys.executable} -m pip install ./src

Defaulting to user installation because normal site-packages is not writeable
Processing ./src
  Created wheel for ShAReD-Net: filename=ShAReD_Net-1.0-py3-none-any.whl size=21517 sha256=3303735362cb393b19079659bd27618999f785e3f30e205883d150f767341366
  Stored in directory: /tmp/pip-ephem-wheel-cache-vwx6_d7u/wheels/22/c3/70/c7c197844357b787f75a5309992d7aa6bb1d79ad298e7a9445
Successfully built ShAReD-Net
  Attempting uninstall: ShAReD-Net
    Found existing installation: ShAReD-Net 1.0
    Uninstalling ShAReD-Net-1.0:
      Successfully uninstalled ShAReD-Net-1.0


In [ ]:
import ShAReD_Net.training.run_train as train
train.main()

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
Init Model

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call

INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = hierarchical_copy, num_packs = 1
Step: 1
Step: 2
Step: 3
Step: 4
Step: 5
Step: 6
Step: 7
Step: 8
Step: 9
Step: 10
Loss: PerReplica:{
  0: <tf.Tensor: shape=(), dtype=float32, numpy=21407528.0>,
  1: <tf.Tensor: shape=(), dtype=float32, numpy=21407528.0>,
  2: <tf.Tensor: shape=(), dtype=float32, numpy=21407528.0>,
  3: <tf.Tensor: shape=(), dtype=float32, numpy=21407528.0>
}
Step: 11
Step: 12
Step: 13
Step: 14
Step: 15
Step: 16
Step: 17
Step: 18
Step: 19
Step: 20
Loss: PerReplica:{
  0: <tf.Tensor: shape=(), dtype=float32, numpy=19554462.0>,
  1: <tf.Tensor: shape=(), dtype=float32, numpy=19554462.0>,
  2: <tf.Tensor: shape=(), dtype=float32, numpy=19554462.0>,
  3: <tf.Tensor: shape=(), dtype=float32, numpy=19554462.0>
}
Step: 21
Step: 22
Step: 23
Step: 24
Step: 25
Step: 26
Step: 27
Step: 28
Step: 29
Step: 30
Loss: PerReplic

In [14]:
!{sys.executable} -m pip freeze

absl-py==0.9.0
asn1crypto==0.24.0
astunparse==1.6.3
attrs==19.3.0
backcall==0.1.0
bleach==3.1.1
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
cryptography==2.1.4
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
enum34==1.1.9
gast==0.3.3
google-auth==1.11.2
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.27.2
h5py==2.10.0
idna==2.6
importlib-metadata==1.5.0
ipykernel==5.1.1
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.0.0
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyter-http-over-ws==0.0.7
Keras-Preprocessing==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.1.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.0
mistune==0.8.4
nbconvert==5.6.1
nbformat==4.4.0
notebook==6.0.3
numpy==1.18.1
oauthlib==3.1.0
opt-einsum==3.2.0
pandocfilters==1.4.2
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==3.0.3
protobuf==3.11.3
pt